# Generated by Django 5.2.11 on 2026-03-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_userprofile_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='two_fa_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
