# Generated by Django 5.2.11 on 2026-03-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_userprofile_two_fa_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='two_fa_method',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=10),
        ),
    ]
